"""Add updated_at to articles

Revision ID: 8f483720b814
Revises: 62f183c78aca
Create Date: 2025-12-20 03:38:08.635352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f483720b814'
down_revision = '62f183c78aca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'updated_at')
    # ### end Alembic commands ###
