name: Build, Publish and Deploy

on:
  push:
    branches: [main, lab2]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/microservice-backend:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/microservice-backend:${{ github.sha }}

  users-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Users API
        uses: docker/build-push-action@v5
        with:
          context: ./users-api
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/microservice-users-api:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/microservice-users-api:${{ github.sha }}

# name: Build, Publish and Deploy

# on:
#   push:
#     branches:
#       - main
#       - lab2

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Log in to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: |
#             ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
#             ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
